site_name: AuraPartnerAI Docs
docs_dir: docs
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - search.suggest
plugins:
  - search
  - git-revision-date-localized
markdown_extensions:
  - admonition
  - pymdownx.superfences
nav:
  - Home: docs/index.md
  - Architecture: docs/architecture.md
  - Changelog: docs/changelog.md
