site_name: AuraPartnerAI Docs
site_url: https://docs.aurapartnerai.com

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.copy
    - content.tabs.link

extra:
  version:
    provider: mike

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
# NOTE: do NOT list "mike" here; Material reads versions via extra.version.provider

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Changelog: changelog.md
