name: Docs (mike deploy)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements-mkdocs.txt ]; then
            pip install -r requirements-mkdocs.txt
          else
            pip install "mkdocs>=1.6" "mkdocs-material>=9.5" mike \
                        "mkdocs-git-revision-date-localized-plugin>=1.2"
          fi

      - name: Git identity
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy vX.Y and set latest
        env:
          VERSION: v0.${{ github.run_number }}
        run: |
          mike deploy --push --update-aliases "$VERSION" latest -m "docs: deploy $VERSION (CI)"
          mike set-default --push latest
          mike list
