name: Protect branches

on:
  push:
    branches:
      - main-clean
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: protect-branches
  cancel-in-progress: false

jobs:
  enforce:
    # запускать только на main-clean либо вручную
    if: github.ref == 'refs/heads/main-clean' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      # Должен быть секрет GH_PAT_ADMIN (classic PAT минимум с правами repo)
      GH_PAT_ADMIN: ${{ secrets.GH_PAT_ADMIN }}
      ACCEPT: application/vnd.github+json
      APIV: 2022-11-28

    steps:
      - name: Validate secret present
        shell: bash
        run: |
          set -euo pipefail
          if [ -z "${GH_PAT_ADMIN:-}" ]; then
            echo "::error::Missing required secret GH_PAT_ADMIN"
            exit 1
          fi

      - name: Context
        shell: bash
        run: |
          set -euo pipefail
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Ref:  $GITHUB_REF"

      - name: Who am I (token sanity)
        shell: bash
        run: |
          set -euo pipefail
          curl -sSf \
            -H "Authorization: Bearer $GH_PAT_ADMIN" \
            -H "Accept: $ACCEPT" \
            https://api.github.com/user | jq '{login, id, type}'

      - name: Protect main-clean (checks, reviews, signatures, linear)
        shell: bash
        run: |
          set -euo pipefail
          OWNER="${GITHUB_REPOSITORY%/*}"
          REPO="${GITHUB_REPOSITORY#*/}"
          BR="main-clean"

          # Основные правила защиты
          curl -sSf -X PUT \
            -H "Authorization: Bearer $GH_PAT_ADMIN" \
            -H "Accept: $ACCEPT" \
            -H "X-GitHub-Api-Version: ${APIV}" \
            "https://api.github.com/repos/${OWNER}/${REPO}/branches/${BR}/protection" \
            -d @- <<'JSON'
          {
            "required_status_checks": {
              "strict": true,
              "checks": [
                {"context":"precommit"},
                {"context":"build-and-test"}
              ]
            },
            "enforce_admins": true,
            "required_pull_request_reviews": {
              "required_approving_review_count": 1,
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": false
            },
            "restrictions": null,
            "required_linear_history": true,
            "allow_force_pushes": false,
            "allow_deletions": false,
            "required_conversation_resolution": true
          }
          JSON

          # Идемпотентно требуем подписанные коммиты
          curl -sS -o /dev/null -w "required_signatures: HTTP %{http_code}\n" -X POST \
            -H "Authorization: Bearer $GH_PAT_ADMIN" \
            -H "Accept: $ACCEPT" \
            -H "X-GitHub-Api-Version: ${APIV}" \
            "https://api.github.com/repos/${OWNER}/${REPO}/branches/${BR}/protection/required_signatures" \
            || true

      - name: Freeze main-legacy (read-only-ish)
        shell: bash
        run: |
          set -euo pipefail
          OWNER="${GITHUB_REPOSITORY%/*}"
          REPO="${GITHUB_REPOSITORY#*/}"

          curl -sSf -X PUT \
            -H "Authorization: Bearer $GH_PAT_ADMIN" \
            -H "Accept: $ACCEPT" \
            -H "X-GitHub-Api-Version: ${APIV}" \
            "https://api.github.com/repos/${OWNER}/${REPO}/branches/main-legacy/protection" \
            -d @- <<'JSON'
          {
            "required_status_checks": null,
            "enforce_admins": true,
            "required_pull_request_reviews": null,
            "restrictions": null,
            "allow_force_pushes": false,
            "allow_deletions": false
          }
          JSON

      - name: Summarize protections (job summary)
        shell: bash
        run: |
          set -euo pipefail
          OWNER="${GITHUB_REPOSITORY%/*}"
          REPO="${GITHUB_REPOSITORY#*/}"

          row () {
            local BR="$1"
            # null-safe: поддерживает и .checks (объекты с context), и .contexts (строки)
            curl -sSf \
              -H "Authorization: Bearer $GH_PAT_ADMIN" \
              -H "Accept: $ACCEPT" \
              -H "X-GitHub-Api-Version: ${APIV}" \
              "https://api.github.com/repos/${OWNER}/${REPO}/branches/${BR}/protection" \
            | jq -r "[\"${BR}\",
                     ((.required_status_checks.checks // .required_status_checks.contexts // []) | map(.context // .) | join(\", \")),
                     ((.required_pull_request_reviews.required_approving_review_count // 0)|tostring),
                     ((.required_signatures.enabled // false)|tostring),
                     ((.required_linear_history.enabled // false)|tostring),
                     ((.required_conversation_resolution.enabled // false)|tostring),
                     ((.enforce_admins.enabled // false)|tostring),
                     ((.allow_force_pushes.enabled // false)|tostring),
                     ((.allow_deletions.enabled // false)|tostring)] | @tsv" \
            || echo -e "${BR}\t-\t0\tfalse\tfalse\tfalse\tfalse\tfalse\tfalse"
          }

          {
            echo "### Branch protections"
            echo
            echo "| Branch | Checks | Reviews | Signatures | Linear | Conversations | Enforce admins | Force push | Deletions |"
            echo "|-------:|--------|---------|------------|--------|---------------|----------------|------------|-----------|"
            IFS=$'\t' read -r b c r s l conv adm fp del <<<"$(row main-clean)"
            echo "| \`${b}\` | ${c} | ${r} | ${s} | ${l} | ${conv} | ${adm} | ${fp} | ${del} |"
            IFS=$'\t' read -r b c r s l conv adm fp del <<<"$(row main-legacy || true)"
            echo "| \`${b}\` | ${c} | ${r} | ${s} | ${l} | ${conv} | ${adm} | ${fp} | ${del} |"
            echo
            echo "<sub>Generated by protect-branches workflow.</sub>"
          } >> "$GITHUB_STEP_SUMMARY"
