name: Protect branches

on:
  push:
    branches: [ main-clean ]
  workflow_dispatch:

permissions:
  contents: read
  administration: write
  pull-requests: write

concurrency:
  group: protect-branches
  cancel-in-progress: false

jobs:
  enforce:
    # выполнять только для main-clean либо когда запущено вручную
    if: github.ref == 'refs/heads/main-clean' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Context
        shell: bash
        run: |
          set -euo pipefail
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Ref:  $GITHUB_REF"

      - name: Protect main-clean (checks, reviews, signatures, linear)
        shell: bash
        run: |
          set -euo pipefail
          HDR="Accept: application/vnd.github+json"
          OWNER="${GITHUB_REPOSITORY%/*}"
          REPO="${GITHUB_REPOSITORY#*/}"
          BR="main-clean"

          # Обновляем защиту ветки
          gh api -X PUT -H "$HDR" repos/$OWNER/$REPO/branches/$BR/protection --input - <<'JSON'
          {
            "required_status_checks": {
              "strict": true,
              "checks": [
                {"context":"precommit"},
                {"context":"build-and-test"}
              ]
            },
            "enforce_admins": true,
            "required_pull_request_reviews": {
              "required_approving_review_count": 1,
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": false
            },
            "restrictions": null,
            "required_linear_history": true,
            "allow_force_pushes": false,
            "allow_deletions": false,
            "required_conversation_resolution": true
          }
          JSON

          # Включаем требование подписанных коммитов (идемпотентно)
          gh api -X POST -H "$HDR" repos/$OWNER/$REPO/branches/$BR/protection/required_signatures || true

      - name: Freeze main-legacy (read-only-ish)
        shell: bash
        continue-on-error: true
        run: |
          set -euo pipefail
          HDR="Accept: application/vnd.github+json"
          OWNER="${GITHUB_REPOSITORY%/*}"
          REPO="${GITHUB_REPOSITORY#*/}"
          BR="main-legacy"

          gh api -X PUT -H "$HDR" repos/$OWNER/$REPO/branches/$BR/protection --input - <<'JSON'
          {
            "required_status_checks": null,
            "enforce_admins": true,
            "required_pull_request_reviews": null,
            "restrictions": null,
            "allow_force_pushes": false,
            "allow_deletions": false
          }
          JSON
      - name: Summarize protections (job summary)
        if: github.ref_name == 'main-clean'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail

          row () {
            local BR="$1"
            gh api -H "$HDR" repos/$OWNER/$REPO/branches/$BR/protection \
              --jq "[\"${BR}\",
                     ((.required_status_checks.checks | map(.context) | join(\", \")) // \"-\"),
                     ((.required_pull_request_reviews.required_approving_review_count // 0)|tostring),
                     ((.required_signatures.enabled // false)|tostring),
                     ((.required_linear_history.enabled // false)|tostring),
                     ((.required_conversation_resolution.enabled // false)|tostring),
                     ((.enforce_admins.enabled // false)|tostring),
                     ((.allow_force_pushes.enabled // false)|tostring),
                     ((.allow_deletions.enabled // false)|tostring)] | @tsv" \
            || echo -e "${BR}\t-\t0\tfalse\tfalse\tfalse\tfalse\tfalse"
          }

          {
            echo "### Branch protections"
            echo
            echo "| Branch | Checks | Reviews | Signatures | Linear | Conversations | Enforce admins | Force push | Deletions |"
            echo "|-------:|--------|---------|------------|--------|---------------|----------------|------------|-----------|"
            IFS=$'\t' read -r b c r s l conv adm fp del <<<"$(row main-clean)"
            echo "| \`${b}\` | ${c} | ${r} | ${s} | ${l} | ${conv} | ${adm} | ${fp} | ${del} |"
            IFS=$'\t' read -r b c r s l conv adm fp del <<<"$(row main-legacy || true)"
            echo "| \`${b}\` | ${c} | ${r} | ${s} | ${l} | ${conv} | ${adm} | ${fp} | ${del} |"
            echo
            echo "<sub>Generated by protect-branches workflow.</sub>"
          } >> "$GITHUB_STEP_SUMMARY"

          echo "::group::Raw JSON (main-clean)"
          gh api -H "$HDR" repos/$OWNER/$REPO/branches/main-clean/protection || true
          echo "::endgroup::"
          echo "::group::Raw JSON (main-legacy)"
          gh api -H "$HDR" repos/$OWNER/$REPO/branches/main-legacy/protection || true
          echo "::endgroup::"
