name: Protect branches

on:
  push:
    branches: [ main-clean ]
  workflow_dispatch:

permissions:
  contents: read
  administration: write
  pull-requests: write

concurrency:
  group: protect-branches
  cancel-in-progress: false

jobs:
  enforce:
    # не выполняться, если ран запущен не из main-clean
    if: github.ref == 'refs/heads/main-clean'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Set headers
        shell: bash
        run: |
          set -euo pipefail
          echo "HDR=Accept: application/vnd.github+json" >> "$GITHUB_ENV"
          echo "APIV=X-GitHub-Api-Version: 2022-11-28"   >> "$GITHUB_ENV"
          echo "OWNER=${{ github.repository_owner }}"     >> "$GITHUB_ENV"
          echo "REPO=${{ github.event.repository.name }}" >> "$GITHUB_ENV"
          echo "BASE=${{ github.event.repository.default_branch }}" >> "$GITHUB_ENV"

      # дальше оставляем твои шаги как были
      - name: Find existing ruleset
        shell: bash
        run: |
          RID=$(gh api -H "$HDR" -H "$APIV" repos/$OWNER/$REPO/rulesets \
            --jq '.[] | select(.enforcement=="active")
                   | select((.conditions.ref_name.include // []) | index("~DEFAULT_BRANCH")
                         or (.conditions.ref_name.include // []) | index("main-clean")) | .id' \
          || true)
          echo "RID=${RID:-}" >> "$GITHUB_ENV"

      # ... остальные шаги без изменений ...
